apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonCICD
spec:
  replicas: 3  # Nombre d'instances
  selector:
    matchLabels:
      app: pythonCICD
  template:
    metadata:
      labels:
        app: pythonCICD
    spec:
      containers:
      - name: pythonCICD-container
        image: mdang/mon-projet:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: mon-projet-service
spec:
  selector:
    app: mon-projet
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort  # Change en LoadBalancer si tu es dans un environnement compatible
