version: '3.8'

services:
  app:
    build: .
    container_name: mon_projet_python
    ports:
      - "5000:5000"  # Assurez-vous que le port correspond à celui que Flask utilise
    volumes:
      - .:/app  # Cela permet de lier le code source local au conteneur pour le développement
    environment:
      - FLASK_APP=app/main.py  # Assurez-vous que l'entrée de votre app Flask est bien spécifiée
      - FLASK_ENV=development  # Mode développement
      - DATABASE_URL=postgresql://user:password@db:5432/mon_projet_db  # URL de connexion à la base de données
    depends_on:
      - db  # Assurez-vous que l'application attend que la base de données soit prête avant de démarrer
    restart: unless-stopped  # Assure que le conteneur redémarre en cas de crash

  db:
    image: postgres:13
    container_name: mon_projet_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mon_projet_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db_data:
    driver: local
