version: '3.8'

services:
  app:
    build: .
    container_name: mon_projet_python
    ports:
      - "5000:5000"  # Assurez-vous que le port correspond à celui que Flask utilise
    volumes:
      - .:/app  # Cela permet de lier le code source local au conteneur pour le développement
    environment:
      - FLASK_ENV=development  # Tu peux ajuster cet environnement en fonction de tes besoins
    depends_on:
      - db  # Si tu as une base de données, par exemple
    restart: unless-stopped  # Assure que le conteneur redémarre en cas de crash

  # Optionnel : un service pour une base de données, si nécessaire (ici, PostgreSQL par exemple)
  db:
    image: postgres:13
    container_name: mon_projet_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mon_projet_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db_data:
    driver: local
