version: '3.8'

services:
  app:
    build: .
    container_name: mon_projet_python
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app/main.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://user:password@db:5432/mon_projet_db
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:13
    container_name: mon_projet_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mon_projet_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db_data:
    driver: local
