name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Déclenche le workflow sur les pushs dans main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Installer Safety
      run: |
        pip install safety

    - name: Vérifier les dépendances pour des vulnérabilités
      run: |
        safety check --file=requirements.txt --ignore 1234  # Optionnel, pour ignorer certaines vulnérabilités
      continue-on-error: true  # Cela permet de continuer même si Safety détecte des vulnérabilités

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build et Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/mon_projet:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/mon_projet:latest

  sonarcloud:
    runs-on: ubuntu-latest
    needs: build  # SonarCloud démarre après le build
    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Install SonarScanner
      run: |
        curl -sSLo sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
        unzip sonar-scanner-cli.zip
        export PATH=$PWD/sonar-scanner-5.0.1.3006-linux/bin:$PATH
        which sonar-scanner || exit 1
        sonar-scanner --version || exit 1

    - name: Analyse SonarCloud
      run: |
        echo "Lancement de l'analyse SonarCloud..."
        export PATH=$PWD/sonar-scanner-5.0.1.3006-linux/bin:$PATH
        sonar-scanner \
          -Dsonar.organization=maneo159 \
          -Dsonar.projectKey=Maneo159_pythonCICD \
          -Dsonar.sources=. \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: [build, sonarcloud]  # Déploiement après SonarCloud
    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Vérifier les images Docker après pull
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/mon_projet:latest
        docker images | grep mon_projet

    - name: Tester si l'image peut être exécutée
      run: |
        docker run -it --rm ${{ secrets.DOCKER_USERNAME }}/mon_projet:latest /bin/sh || echo "Erreur lors du test de l'image"

    - name: Déploiement du conteneur
      run: |
        docker stop mon_projet || true
        docker rm mon_projet || true
        docker run -d -p 5000:5000 --name mon_projet ${{ secrets.DOCKER_USERNAME }}/mon_projet:latest

    - name: Vérifier les conteneurs en cours d'exécution
      run: |
        docker ps -a

    - name: Vérifier les logs du conteneur
      run: |
        docker logs mon_projet || echo "Aucun log trouvé"