name: Deploy to Server

on:
  push:
    branches:
      - main  # ou la branche sur laquelle tu veux déployer

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/mon_projet:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/mon_projet:latest

    - name: Deploy to Server
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/mon_projet:latest
        docker stop mon_projet || true
        docker rm mon_projet || true
        docker run -d -p 5000:5000 --name mon_projet ${{ secrets.DOCKER_USERNAME }}/mon_projet:latest
 
