name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Installer Safety
      run: |
        pip install safety

    - name: Vérifier les dépendances pour des vulnérabilités
      run: |
        safety check --file=requirements.txt --ignore 1234
      continue-on-error: true

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build et Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/mon_projet:${{ github.run_number }} .
        docker tag ${{ secrets.DOCKER_USERNAME }}/mon_projet:${{ github.run_number }} ${{ secrets.DOCKER_USERNAME }}/mon_projet:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/mon_projet:${{ github.run_number }}
        docker push ${{ secrets.DOCKER_USERNAME }}/mon_projet:latest

  sonarcloud:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Install SonarScanner
      run: |
        curl -sSLo sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
        unzip sonar-scanner-cli.zip
        export PATH=$PWD/sonar-scanner-5.0.1.3006-linux/bin:$PATH
        which sonar-scanner || exit 1
        sonar-scanner --version || exit 1

    - name: Analyse SonarCloud
      run: |
        echo "Lancement de l'analyse SonarCloud..."
        export PATH=$PWD/sonar-scanner-5.0.1.3006-linux/bin:$PATH
        sonar-scanner \
          -Dsonar.organization=maneo159 \
          -Dsonar.projectKey=Maneo159_pythonCICD \
          -Dsonar.sources=. \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: [build, sonarcloud]
    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Installer Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Lancer Docker Compose en local
      run: |
        docker-compose up --build -d  # Lance le conteneur en mode détaché
        docker-compose ps  # Vérifie les conteneurs en cours d'exécution
        docker-compose logs app  # Affiche les logs du conteneur 'app'

    - name: Vérifier que l'application fonctionne
      run: |
        curl http://localhost:5000  # Change le port si nécessaire

    - name: Arrêter Docker Compose
      run: |
        docker-compose down  # Arrête les conteneurs
