name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Déclenche le workflow sur les pushs dans main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build et Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/mon_projet:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/mon_projet:latest

  sonarcloud:
    runs-on: ubuntu-latest
    needs: build  # SonarCloud démarre après le build
    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Analyse SonarCloud
      run: |
        sonar-scanner \
          -Dsonar.organization=Maneo159 \
          -Dsonar.projectKey=pythonCICD \
          -Dsonar.sources=. \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}


  deploy:
    runs-on: ubuntu-latest
    needs: [build, sonarcloud]  # Déploiement après SonarCloud
    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Deploy to Server
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/mon_projet:latest
        docker stop mon_projet || true
        docker rm mon_projet || true
        docker run -d -p 5000:5000 --name mon_projet ${{ secrets.DOCKER_USERNAME }}/mon_projet:latest
