name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # ou la version que tu utilises

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Si tu projet utilise un fichier requirements.txt

    - name: Install pytest
      run: pip install pytest  # Installe pytest dans l'environnement

    - name: Run tests with pytest
      run: pytest  # Exécute les tests
