name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Installer les dépendances
      run: |
        pip install -r requirements.txt

  tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Installer les dépendances
      run: |
        pip install -r requirements.txt

    - name: Exécuter les tests unitaires
      run: |
        pytest --maxfail=1 --disable-warnings -q

  security:
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Installer Safety
      run: |
        pip install safety

    - name: Vérifier les dépendances pour des vulnérabilités
      run: |
        safety check --file=requirements.txt --ignore 1234
      continue-on-error: true

  sonarcloud:
    runs-on: ubuntu-latest
    needs: security
    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Install SonarScanner
      run: |
        curl -sSLo sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
        unzip sonar-scanner-cli.zip
        export PATH=$PWD/sonar-scanner-5.0.1.3006-linux/bin:$PATH
        which sonar-scanner || exit 1
        sonar-scanner --version || exit 1

    - name: Analyse SonarCloud
      run: |
        echo "Lancement de l'analyse SonarCloud..."
        export PATH=$PWD/sonar-scanner-5.0.1.3006-linux/bin:$PATH
        sonar-scanner \
          -Dsonar.organization=maneo159 \
          -Dsonar.projectKey=Maneo159_pythonCICD \
          -Dsonar.sources=. \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: sonarcloud
    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Installer Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Lancer Docker Compose en local
      run: |
        docker-compose up --build -d
        docker-compose ps
        docker-compose logs app

    - name: Vérifier que l'application fonctionne
      run: |
        curl http://127.0.0.1:5000/users
